// Generated by CIRCT eade0de
module max3(	// hw/max3.mlir:1:1
  input  [15:0] a,	// hw/max3.mlir:1:20
                b,	// hw/max3.mlir:1:33
                c,	// hw/max3.mlir:1:46
  output [15:0] result	// hw/max3.mlir:1:60
);

  wire [15:0] _GEN = $signed(a) > $signed(b) ? a : b;	// hw/max3.mlir:3:9, :4:9
  assign result = $signed(_GEN) > $signed(c) ? _GEN : c;	// hw/max3.mlir:4:9, :8:9, :9:11, :11:3
endmodule

